# Generated by Django 5.0.1 on 2024-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_rating_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.TextField(blank=True, null=True)),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('coupon_description', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('usage_count', models.PositiveBigIntegerField(default=0)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupon', to='item.item')),
            ],
        ),
    ]
