# Generated by Django 5.0.1 on 2024-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
