# Generated by Django 4.2.10 on 2024-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
