# Generated by Django 4.2.10 on 2024-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthtip_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
