# Generated by Django 5.0.2 on 2024-03-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otp_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
